= Project

There are two kinds of `projects` in Polylith: development and deployable.

* The xref:development.adoc[development] project:
** Where you work with the code, often from a REPL.
** Described in the workspace `./deps.edn` which:
*** Specifies all bricks and project libraries used by the project.
*** Optionally defines xref:profile.adoc[profiles].
** Source code to support development (not part of any component or base) lives under the `./development` directory.

* A deployable project:
** Used to build deployable xref:artifacts.adoc[artifacts], e.g.,: lambda functions, REST APIs, tools, etc.
** Has its own directory under the `./projects` directory
** Has a `deps.edn` specifying the bricks and libraries used by the deployable project.
** Can optionally have a `resources` directory.
** If the specified bricks contain any tests, they are run when you execute the xref:commands.adoc#test[test] command.
** If the deployable project has any tests of its own, they live in its `test` directory, e.g., `projects/my-project/test`.
** It's discouraged for a deployable project to have a `src` directory, e.g., `projects/my-project/src`, since all production code should normally only live in bricks.

The `:project` key in `./workspace.edn` configures project aliases and, optionally, how `poly` should run your xref:testing.adoc[tests].

Let's carry on with our tutorial.
Run the following xref:commands#create-project[create project] command:

[source,shell]
----
poly create project name:command-line
----

Your workspace should now look like this:

[source,shell]
----
example
├── bases
│   └── cli
│       ├── deps.edn
│       ├── resources
│       │   └── cli
│       ├── src
│       │   └── se
│       │       └── example
│       │           └── cli
│       │               └── core.clj
│       └── test
│           └── se
│               └── example
│                   └── cli
│                       └── core_test.clj
├── components
│   └── user
│       ├── deps.edn
│       ├── resources
│       │   └── user
│       ├── src
│       │   └── se
│       │       └── example
│       │           └── user
│       │               ├── core.clj
│       │               └── interface.clj
│       └── test
│           └── se
│               └── example
│                   └── user
│                       └── interface_test.clj
├── deps.edn
├── development
│   └── src
│       └── dev
│           └── lisa.clj
├── logo.png
├── projects
│   └── command-line # <1>
│       └── deps.edn
├── readme.md
└── workspace.edn
----
<1> new `command-line` project

The `poly` tool helpfully reminds us:

[source,shell]
----
  It's recommended to add an alias to :projects in ./workspace.edn for the command-line project.
----

If you don't add an alias for the `command-line` project, its heading will default to `?1` when running the xref:commands.adoc#info[info] command.
Go ahead and add an alias in your `./workspace.edn`:

[source,clojure]
----
  {...
   :projects {"development" {:alias "dev"}
              "command-line" {:alias "cli"}}} <1>
----
<1> Add the `cl` `alias` for the `command-line` project

Now add `user` and `cli` by editing `projects/command-line/deps.edn`:

[source,clojure]
----
{:deps {poly/user {:local/root "../../components/user"} ;; <1>
        poly/cli  {:local/root "../../bases/cli"} ;; <2>

        org.clojure/clojure {:mvn/version "1.11.1"}}
----
<1> Add `user` component
<2> Add `cli` base

****
The `:local/root` paths begin with `../../` because the `components` and `bases` directories are two levels up relative to `projects/command-line` directory.
****

When you run the xref:commands.adoc#test[test] command, `poly` will determine which tests should run.
If you want to run tests for each deployable project outside of `poly` using Clojure's tools.deps, you must specify the test paths in your workspace `./deps.edn`.

[NOTE]
====
Each `./projects/**/deps.edn` specifies what bricks to include via `:local/root` dependencies.
The `poly` xref:commands.adoc[test] command determines the appropriate test dependencies from each referenced brick's `deps.edn`.

But Clojure's tools.deps does not include test dependencies from `:local/root` dependencies.
To support IDEs and other tooling, you must compensate by adding your brick tests as separate paths in your workspace `deps.edn`, just as you did for your xref:component.adoc#add-to-deps-edn[user component] and xref:base.adoc#add-to-deps-edn[cli base].
====

How you specify dependency to bricks differs based on the project type:

* For the development project: `./deps.edn > :aliases > :dev > :extra-deps`
* For deployable projects: `./projects/PROJECT-DIR/deps.edn > :deps`
